import { Market } from "../../types";

export const marketDataService = {
  getMarkets: async (): Promise<Market[]> => [
    {
      symbol: "AAPL",
      name: "Apple Inc.",
      price: 193.4,
      change: 2.8,
      market: "us",
    },
    {
      symbol: "NVDA",
      name: "NVIDIA Corp.",
      price: 120.75,
      change: 5.1,
      market: "us",
    },
    {
      symbol: "TSLA",
      name: "Tesla Inc.",
      price: 247.1,
      change: -1.3,
      market: "us",
    },
    {
      symbol: "MSFT",
      name: "Microsoft Corp.",
      price: 334.2,
      change: 1.5,
      market: "us",
    },
    {
      symbol: "AMZN",
      name: "Amazon.com Inc.",
      price: 135.6,
      change: 0.9,
      market: "us",
    },
    {
      symbol: "GOOGL",
      name: "Alphabet Inc.",
      price: 132.8,
      change: -0.4,
      market: "us",
    },
    {
      symbol: "META",
      name: "Meta Platforms",
      price: 196.3,
      change: 0.7,
      market: "us",
    },
    {
      symbol: "THYAO",
      name: "Türk Hava Yolları",
      price: 286.5,
      change: 1.9,
      market: "bist",
    },
    {
      symbol: "ASELS",
      name: "Aselsan",
      price: 62.4,
      change: 3.2,
      market: "bist",
    },
    {
      symbol: "BIMAS",
      name: "BİM Mağazalar",
      price: 498.75,
      change: -0.6,
      market: "bist",
    },
    {
      symbol: "AKBNK",
      name: "Akbank",
      price: 58.9,
      change: 1.1,
      market: "bist",
    },
    {
      symbol: "TUPRS",
      name: "Tüpraş",
      price: 164.2,
      change: -1.4,
      market: "bist",
    },
    {
      symbol: "TCD",
      name: "TEB Portföy Hisse Fonu",
      price: 4.82,
      change: 0.8,
      market: "funds",
    },
    {
      symbol: "MAC",
      name: "Marmara Capital Hisse Fonu",
      price: 3.64,
      change: 1.2,
      market: "funds",
    },
    {
      symbol: "AFT",
      name: "Ak Portföy Teknoloji Fonu",
      price: 2.91,
      change: 0.4,
      market: "funds",
    },
    {
      symbol: "BTC",
      name: "Bitcoin",
      price: 68420,
      change: 2.6,
      market: "crypto",
    },
    {
      symbol: "ETH",
      name: "Ethereum",
      price: 3640,
      change: 1.8,
      market: "crypto",
    },
    {
      symbol: "SOL",
      name: "Solana",
      price: 174.25,
      change: -0.9,
      market: "crypto",
    },
    { symbol: "XRP", name: "XRP", price: 0.58, change: 3.5, market: "crypto" },
  ],
  getSymbols: async (): Promise<string[]> => [
    "AAPL",
    "NVDA",
    "TSLA",
    "MSFT",
    "AMZN",
    "GOOGL",
    "META",
  ],
};
