export const portfolioService = {
  getPortfolio: async () => ({
    totalBalance: 24850,
    availableCash: 8420,
    dailyChange: 310,
    returnPercent: 12.4,
  }),
  getPositions: async () => [
    {
      symbol: 'AAPL',
      name: 'Apple Inc.',
      shares: 24,
      avgCost: 178.6,
      currentPrice: 193.4,
      changePercent: 2.8,
      marketValue: 4641.6,
      allocation: 18.7,
    },
    {
      symbol: 'NVDA',
      name: 'NVIDIA Corp.',
      shares: 12,
      avgCost: 104.2,
      currentPrice: 120.75,
      changePercent: 5.1,
      marketValue: 1449,
      allocation: 5.8,
    },
    {
      symbol: 'TSLA',
      name: 'Tesla Inc.',
      shares: 18,
      avgCost: 252.9,
      currentPrice: 247.1,
      changePercent: -1.3,
      marketValue: 4447.8,
      allocation: 17.9,
    },
    {
      symbol: 'MSFT',
      name: 'Microsoft Corp.',
      shares: 10,
      avgCost: 320.5,
      currentPrice: 334.2,
      changePercent: 1.5,
      marketValue: 3342,
      allocation: 13.5,
    },
    {
      symbol: 'AMZN',
      name: 'Amazon.com Inc.',
      shares: 5,
      avgCost: 129.4,
      currentPrice: 135.6,
      changePercent: 0.9,
      marketValue: 678,
      allocation: 2.8,
    },
  ],
};
